config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  root "galleries#index"

  resources :galleries do
    resources :images
  end

  resources :images, only: [] do 
    resources :comments, only: [:create]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :image

  def self.by_most_recent
      order(created_at: :desc)
  end
  validates :content, presence: :true, uniqueness: :true
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many( :images,{ dependent: :destroy})


  validates :name, presence: true, uniqueness: :true
  validates :description, presence: true, uniqueness: true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery
  belongs_to :user

  has_many :comments

  validates :name, presence: :true, uniqueness: :true
  validates :url, presence: :true, uniqueness: :true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :images
  has_many :comments

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers


  before_action :require_login, only:[:show]
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @image = Image.find(params[:image_id])
    @comment = @image.comments.new(comment_prams)
    
    if @comment.save
      redirect_to [@image.gallery, @image]
    else
      @gallery = @image.gallery
      render "images/show"
    end
  end

  def comment_prams
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index 
    @galleries = Gallery.all
  end

  def show
    @gallery = Gallery.find(params[:id])
  end

  def new
    @gallery = Gallery.new
  end

  def create 
    gallery_params = params.require(:gallery).permit(:name, :description, :cover_image)
    @gallery = Gallery.create(gallery_params)

    if @gallery.save
      redirect_to gallery_path(@gallery)
    else
      render(:new)
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def update
    @gallery = Gallery.find(params[:id])
    gallery_params = params.require(:gallery).permit(:name, :description, :cover_image)
    @gallery.update(gallery_params)

    redirect_to gallery_path(@gallery)
  end

  def destroy
    gallery = Gallery.find(params[:id])
    gallery.destroy
    redirect_to "/galleries"
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.new
  end

  def create
    @gallery = Gallery.find(params[:gallery_id])
    @image = @gallery.images.create(image_params)
    @image.user = current_user

    if @image.save
      redirect_to gallery_path(@gallery)
    else
      render :new
    end
  end

  def update
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.find(params[:id])

    if @image.update(image_params)
      redirect_to gallery_image_path(@gallery, @image)
    else
      render :edit
    end
  end

  def edit
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.find(params[:id])
  end

  def destroy
    gallery = Gallery.find(params[:gallery_id])
    image = Image.find(params[:id])
    image.destroy

    redirect_to gallery_path(gallery)
  end

  def show
    @gallery = Gallery.find(params[:gallery_id])
    @image = Image.find(params[:id])
    @comment = Comment.new
  end

  private
  def image_params
    params.require(:image).permit(:name, :description, :url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_form_errors.html.erb
  <% if object.errors.any? %>
  <div>
    <p> We could not save your <%= object.class.to_s %> </p>
    <% object.errors.full_messages.each do |error_message| %> 
        <li> <%= error_message %> </li>
    <% end %>
  <% end %>
</div>

app/views/comments/_comment.html.erb
<div>
  <p><%= comment.content %></p>
  <p>--by <%= "#{comment.user.email}   #{time_ago_in_words(comment.created_at)}" %></p>
  <% if current_user.email == comment.user.email %>
    <p> delete me </p>
  <% end %>
</div>

app/views/galleries/_form.html.erb
<%= form_for gallery do |form| %>

  <%= render "form_errors", object: gallery %>
<div>
  <%= form.label :name %>
  <%= form.text_field :name, placeholder: @gallery.name%>
</div>

<div>
  <%= form.label :description %>
  <%= form.text_area :description, placeholder: @gallery.description%>
</div>

<div>
  <%= form.label :cover_image %>
  <%= form.text_field :cover_image, placeholder: @gallery.cover_image %>
</div>

<%= form.submit "update gallery" %>
<% end %>

app/views/galleries/delete.html.erb
<h1> delete </h1>

app/views/galleries/edit.html.erb
<h1> Edit <%= @gallery.name %> </h1>

<%= render "form", gallery: @gallery %>

app/views/galleries/index.html.erb
<h1> Galleries </h1>
<p> A collection of things</p>

<ul>
  <% @galleries.each do |gallery| %>
    <li>
  <%= link_to gallery.name, gallery_path(gallery)  %>
  </li>
<% end %>
</ul>

<%= link_to "New Gallery", new_gallery_path %>

app/views/galleries/new.html.erb
<h1> New Gallery </h1>

<%= render "form", gallery: @gallery %>

app/views/galleries/show.html.erb
<h1> <%= @gallery.name %> </h1>
<p> <%= @gallery.description %> </p>
<div> 
  <%= image_tag @gallery.cover_image ,width:250 %>
</div>
<div>
  <%= link_to "Index", "/galleries"%>
</div>
<div>
  <%= link_to "Edit Gallery", edit_gallery_path(@gallery) %>
  <%= link_to "add image", new_gallery_image_path(@gallery) %>
</div>
<br>
<div>
  <form action="/galleries/<%= @gallery.id %>" method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete this gallery">
</div>
<div>
  <% @gallery.images.each do |image| %>
    <%= link_to [@gallery, image]  do %>
      <ul><%= image_tag image.url ,width: 350 %></ul>
    <% end %>
  <% end %>
</div>

app/views/images/_form.html.erb
<%= form_for [gallery, image] do |form| %>

  <% if image.errors.any? %>
  <div>
    <p> We could not save your <%= image.class.to_s %> </p>
    <% image.errors.full_messages.each do |error_message| %> 
        <li> <%= error_message %> </li>
    <% end %>
  </div>
  <% end %>

<div>
  <%= form.label :name %>
  <%= form.text_field :name, placeholder: image.name%>
</div>

<div>
  <%= form.label :description %>
  <%= form.text_area :description, placeholder: image.description%>
</div>

<div>
  <%= form.label :url %>
  <%= form.text_field :url, placeholder: image.url %>
</div>

<%= form.submit "submit" %>
<% end %>

app/views/images/edit.html.erb
<h1> Edit <%= @image.name %> </h1> 

<%= render "form", gallery: @gallery, image: @image %>

app/views/images/new.html.erb
<h1> Add Image to <%= @gallery.name %> </h1>

<%= render "form", gallery: @gallery, image: @image %>

app/views/images/show.html.erb
<h1> <%= @image.name %> </h1>

<p> <%= @image.description %> </p>
<div>
  <%= link_to "back to gallery", gallery_path(@gallery) %>
  <%= link_to "edit Image" , edit_gallery_image_path(@gallery,  @image)%>
</div>
<div>
  <form action="/galleries/<%= @gallery.id %>/images/<%= @image.id %> " method="POST">
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Delete this Image">
  </form>
</div>

<div>
<%= image_tag @image.url, width: 650 %>
</div>

<%= render "form_errors", object: @comment  %>

<%= form_for [@image, @comment] do |f| %>
  <%= f.label :content, "Comment" %>
  <%= f.text_area :content %>
  <%= f.submit %>
<% end %>

<%= render @image.comments.by_most_recent %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Pixtr</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
  <h3> <%= current_user.email %>
<%= button_to "sign out", session_path, method: :destroy %> 
<%else %>
    <%= link_to "sign up", new_user_path %>
  <%= link_to "sign_in", new_session_path %>
<% end %>
</h3>

<br>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>